# Generated by Django 4.1.2 on 2022-10-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=None)),
                ('mail', models.EmailField(max_length=40)),
                ('passw', models.CharField(max_length=30)),
            ],
        ),
    ]
