# Generated by Django 4.1.2 on 2022-12-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwsapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mail', models.EmailField(max_length=60)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=80)),
                ('doa', models.DateTimeField()),
                ('problem', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='img',
            field=models.ImageField(default='image1.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
