# Generated by Django 4.1.2 on 2022-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwsapp', '0004_prescriptions_alter_userdetails_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='pro',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='mob',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='pres',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='img',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to=''),
        ),
    ]
