# Generated by Django 4.1.2 on 2022-12-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwsapp', '0007_alter_userdetails_mob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='mob',
            new_name='mobile',
        ),
    ]
