# Generated by Django 4.1.2 on 2022-12-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwsapp', '0008_rename_mob_userdetails_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='mobile',
        ),
    ]
