# Generated by Django 4.1.2 on 2022-12-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwsapp', '0010_userdetails_mobile_alter_prescriptions_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='pres',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='pro',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
