# Generated by Django 4.1.2 on 2022-12-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwsapp', '0013_userdetails_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptions',
            old_name='pro',
            new_name='prob',
        ),
    ]
