# Generated by Django 4.1.2 on 2022-12-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwsapp', '0014_rename_pro_prescriptions_prob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='patientname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
