# Generated by Django 4.1.2 on 2022-12-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwsapp', '0016_alter_appointments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='name',
            new_name='fullname',
        ),
    ]
