# Generated by Django 4.1.2 on 2022-12-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwsapp', '0017_rename_name_appointments_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='fullname',
            new_name='name',
        ),
    ]
